/* !!!! DO NOT MODIFY THIS FILE !!!! * This file was generated by EntGen.exe. Your changes will be overridden on the next build
 * If you want to change this file, change the relevant entity config file, or change the
 * EntityDef.hbs template file
 */
#include "EntityCreator.h"


Entity* createEntity(int id)
{
    switch(id)
    {
        case 1:
        {
            Entity* e = new Entity;
            //Solid = true
            e->components.push_back(new SolidComponent(true));
            //Health = 20
            e->components.push_back(new HealthComponent(20));
            //Model = "Skeleton.obj"
            e->components.push_back(new ModelComponent("Skeleton.obj"));
        }
        case 2:
        {
            Entity* e = new Entity;
            //Solid = false
            e->components.push_back(new SolidComponent(false));
            //Model = "Ghost.obj"
            e->components.push_back(new ModelComponent("Ghost.obj"));
        }
    }
}
